//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ruangong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public string password { get; set; }
        public string stuname { get; set; }
        public string stunum { get; set; }
        public Nullable<int> sign { get; set; }
        public Nullable<int> signall { get; set; }
        public Nullable<int> leave { get; set; }
        public Nullable<int> leaveall { get; set; }
    }
}
